### ISSUE TITLE
Could not create model

### ISSUE THREAD

**Issue by chanansh** [ricklupton/ipysankeywidget#11]
Could not create model:
Model name	SankeyModel
Model module	jupyter-sankey-widget
Model module version	*
Script error for "jupyter-sankey-widget" http://requirejs.org/docs/errors.html#scripterror

Windows 10.
pip list:
alabaster (0.7.7)
anaconda-client (1.4.0)
anaconda-navigator (1.1.0)
argcomplete (1.0.0)
astropy (1.1.2)
Babel (2.2.0)
beautifulsoup4 (4.4.1)
bitarray (0.8.1)
blaze (0.9.1)
bokeh (0.11.1)
boto (2.39.0)
Bottlechest (0.7.1)
Bottleneck (1.0.0)
cffi (1.5.2)
chardet (2.3.0)
chest (0.2.3)
cloudpickle (0.1.1)
clyent (1.2.1)
colorama (0.3.7)
comtypes (1.1.2)
conda (4.3.16)
conda-build (1.20.0)
conda-manager (0.3.1)
configobj (5.0.6)
cryptography (1.4)
cycler (0.10.0)
Cython (0.23.4)
cytoolz (0.7.5)
dask (0.8.1)
datashape (0.5.1)
decorator (4.0.9)
dill (0.2.4)
docutils (0.12)
dynd (c328ab7)
et-xmlfile (1.0.1)
fastcache (1.0.2)
Flask (0.10.1)
Flask-Cors (2.1.2)
gevent (1.1.0)
greenlet (0.4.9)
h5py (2.5.0)
HeapDict (1.0.0)
idna (2.0)
ipykernel (4.6.1)
ipysankeywidget (0.1.6)
ipython (4.1.2)
ipython-d3-sankey (0.1.1)
ipython-genutils (0.1.0)
ipywidgets (6.0.0)
itsdangerous (0.24)
jdcal (1.2)
jedi (0.9.0)
Jinja2 (2.8)
jsonschema (2.4.0)
jupyter (1.0.0)
jupyter-client (4.2.2)
jupyter-console (4.1.1)
jupyter-core (4.1.0)
jupyter-pip (0.3)
llvmlite (0.9.0)
locket (0.2.0)
lxml (3.6.0)
MarkupSafe (0.23)
matplotlib (1.5.1)
menuinst (1.3.2)
mistune (0.7.2)
mpmath (0.19)
multipledispatch (0.4.8)
nbconvert (4.1.0)
nbformat (4.3.0)
networkx (1.11)
nltk (3.2)
nose (1.3.7)
notebook (5.0.0)
numba (0.24.0)
numexpr (2.5)
numpy (1.10.4)
odo (0.4.2)
openpyxl (2.3.2)
Orange (3.2.dev0+dfc525c)
pandas (0.18.0)
partd (0.3.2)
path.py (0.0.0)
patsy (0.4.0)
pep8 (1.7.0)
pickleshare (0.5)
Pillow (3.1.1)
pip (9.0.1)
ply (3.8)
psutil (4.1.0)
py (1.4.31)
pyasn1 (0.1.9)
pycosat (0.6.1)
pycparser (2.14)
pycrypto (2.6.1)
pyflakes (1.1.0)
Pygments (2.1.1)
pyOpenSSL (16.2.0)
pyparsing (2.0.3)
pyqtgraph (0.9.10)
pyreadline (2.1)
pytest (2.8.5)
python-dateutil (2.5.1)
pytz (2016.2)
pywin32 (220)
PyYAML (3.11)
pyzmq (15.2.0)
QtAwesome (0.3.2)
qtconsole (4.2.0)
QtPy (1.0)
requests (2.12.4)
rope-py3k (0.9.4.post1)
scikit-image (0.12.3)
scikit-learn (0.17.1)
scipy (0.17.0)
seaborn (0.7.0)
setuptools (20.3)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.10.0)
snowballstemmer (1.2.1)
sockjs-tornado (1.0.1)
Sphinx (1.3.1)
sphinx-rtd-theme (0.1.9)
spyder (2.3.8)
SQLAlchemy (1.0.12)
statsmodels (0.6.1)
sympy (1.0)
tables (3.2.2)
toolz (0.7.4)
tornado (4.3)
tqdm (4.11.2)
traitlets (4.3.2)
unicodecsv (0.14.1)
update (0.4.4)
Werkzeug (0.11.4)
wheel (0.29.0)
widgetsnbextension (2.0.0)
xlrd (0.9.4)
XlsxWriter (0.8.4)
xlwings (0.7.0)
xlwt (1.0.0)

**Comment by Akshaysehgal2005** [comment]
Same issue. Ran the whole code step by step. I think i maybe doing something wrong.

**Comment by aloosley** [comment]
Everything worked up until today.  Now I get the same issue.

**Comment by ricklupton** [comment]
Thanks for the reports. Usually when there is an error with widgets there are more details visible in the developer console in the browser. Are you able to look there and tell me what the error is?

**Comment by ricklupton** [comment]
I've just tried again with a fresh install of Anaconda on Windows 10 with Chrome 60. This is exactly what I did, in case it lets you see something that's different on your system.

1. Installed Anaconda 4.4.0 64 bit (Python 3.6).

2. In the Anaconda prompt:
```
(C:\Users\rick\Anaconda3) C:\Users\rick>pip install ipysankeywidget
Collecting ipysankeywidget
  Downloading ipysankeywidget-0.2.1-py2.py3-none-any.whl (695kB)
    100% |████████████████████████████████| 696kB 852kB/s
Requirement already satisfied: ipywidgets>=5.1.3 in c:\users\rick\anaconda3\lib\site-packages (from ipysankeywidget)
Installing collected packages: ipysankeywidget
Successfully installed ipysankeywidget-0.2.1

(C:\Users\rick\Anaconda3) C:\Users\rick>jupyter nbextension enable --py --sys-prefix ipysankeywidget
Enabling notebook extension jupyter-sankey-widget/extension...
      - Validating: ok

(C:\Users\rick\Anaconda3) C:\Users\rick>jupyter nbextension list
Known nbextensions:
  config dir: C:\Users\rick\Anaconda3\etc\jupyter\nbconfig
    notebook section
      jupyter-js-widgets/extension enabled
      - Validating: ok
      jupyter-sankey-widget/extension enabled
      - Validating: ok

(C:\Users\rick\Anaconda3) C:\Users\rick>jupyter notebook
[...]
```

3. Download the ipysankeywidget examples: https://github.com/ricklupton/ipysankeywidget/archive/master.zip

4. In Jupyter notebook, navigate to `examples/Simple example.ipynb`, step through cells by pressing Shift-Enter.

My package versions:
```
(C:\Users\rick\Anaconda3) C:\Users\rick>pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
alabaster (0.7.10)
anaconda-client (1.6.3)
anaconda-navigator (1.6.2)
anaconda-project (0.6.0)
asn1crypto (0.22.0)
astroid (1.4.9)
astropy (1.3.2)
Babel (2.4.0)
backports.shutil-get-terminal-size (1.0.0)
beautifulsoup4 (4.6.0)
bitarray (0.8.1)
blaze (0.10.1)
bleach (1.5.0)
bokeh (0.12.5)
boto (2.46.1)
Bottleneck (1.2.1)
cffi (1.10.0)
chardet (3.0.3)
click (6.7)
cloudpickle (0.2.2)
clyent (1.2.2)
colorama (0.3.9)
comtypes (1.1.2)
conda (4.3.21)
contextlib2 (0.5.5)
cryptography (1.8.1)
cycler (0.10.0)
Cython (0.25.2)
cytoolz (0.8.2)
dask (0.14.3)
datashape (0.5.4)
decorator (4.0.11)
distributed (1.16.3)
docutils (0.13.1)
entrypoints (0.2.2)
et-xmlfile (1.0.1)
fastcache (1.0.2)
Flask (0.12.2)
Flask-Cors (3.0.2)
gevent (1.2.1)
greenlet (0.4.12)
h5py (2.7.0)
HeapDict (1.0.0)
html5lib (0.999)
idna (2.5)
imagesize (0.7.1)
ipykernel (4.6.1)
ipysankeywidget (0.2.1)
ipython (5.3.0)
ipython-genutils (0.2.0)
ipywidgets (6.0.0)
isort (4.2.5)
itsdangerous (0.24)
jdcal (1.3)
jedi (0.10.2)
Jinja2 (2.9.6)
jsonschema (2.6.0)
jupyter (1.0.0)
jupyter-client (5.0.1)
jupyter-console (5.1.0)
jupyter-core (4.3.0)
lazy-object-proxy (1.2.2)
llvmlite (0.18.0)
locket (0.2.0)
lxml (3.7.3)
MarkupSafe (0.23)
matplotlib (2.0.2)
menuinst (1.4.7)
mistune (0.7.4)
mpmath (0.19)
msgpack-python (0.4.8)
multipledispatch (0.4.9)
navigator-updater (0.1.0)
nbconvert (5.1.1)
nbformat (4.3.0)
networkx (1.11)
nltk (3.2.3)
nose (1.3.7)
notebook (5.0.0)
numba (0.33.0)
numexpr (2.6.2)
numpy (1.12.1)
numpydoc (0.6.0)
odo (0.5.0)
olefile (0.44)
openpyxl (2.4.7)
packaging (16.8)
pandas (0.20.1)
pandocfilters (1.4.1)
partd (0.3.8)
path.py (10.3.1)
pathlib2 (2.2.1)
patsy (0.4.1)
pep8 (1.7.0)
pickleshare (0.7.4)
Pillow (4.1.1)
pip (9.0.1)
ply (3.10)
prompt-toolkit (1.0.14)
psutil (5.2.2)
py (1.4.33)
pycosat (0.6.2)
pycparser (2.17)
pycrypto (2.6.1)
pycurl (7.43.0)
pyflakes (1.5.0)
Pygments (2.2.0)
pylint (1.6.4)
pyodbc (4.0.16)
pyOpenSSL (17.0.0)
pyparsing (2.1.4)
pytest (3.0.7)
python-dateutil (2.6.0)
pytz (2017.2)
PyWavelets (0.5.2)
pywin32 (220)
PyYAML (3.12)
pyzmq (16.0.2)
QtAwesome (0.4.4)
qtconsole (4.3.0)
QtPy (1.2.1)
requests (2.14.2)
rope-py3k (0.9.4.post1)
scikit-image (0.13.0)
scikit-learn (0.18.1)
scipy (0.19.0)
seaborn (0.7.1)
setuptools (27.2.0)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.10.0)
snowballstemmer (1.2.1)
sortedcollections (0.5.3)
sortedcontainers (1.5.7)
sphinx (1.5.6)
spyder (3.1.4)
SQLAlchemy (1.1.9)
statsmodels (0.8.0)
sympy (1.0)
tables (3.2.2)
tblib (1.3.2)
testpath (0.3)
toolz (0.8.2)
tornado (4.5.1)
traitlets (4.3.2)
unicodecsv (0.14.1)
wcwidth (0.1.7)
Werkzeug (0.12.2)
wheel (0.29.0)
widgetsnbextension (2.0.0)
win-unicode-console (0.5)
wrapt (1.10.10)
xlrd (1.0.0)
XlsxWriter (0.9.6)
xlwings (0.10.4)
xlwt (1.2.0)
zict (0.1.2)
```

**Comment by ricklupton** [comment]
@chanansh I notice you have an old version of ipysankeywidget (0.1.6). Can you upgrade to the latest and see if that helps?

Also you have the old ipython-d3-sankey installed, which shouldn't interfere, but you could try removing that. Check for old versions of the widget installed using `jupyter nbextension list` and `jupyter paths`

**Comment by snorfalorpagus** [comment]
I was getting the same error. Turns out I hadn't done:

`jupyter nbextension enable --py --sys-prefix ipysankeywidget`

**Comment by DenysVincon** [comment]
Is it possible to install and use the widgets in python 2.7? Apparently it doesn't work (I'm on ubuntu with firefox).

**Comment by ricklupton** [comment]
@DenysVincon Yes it should work on Python 2. If it's not working for you perhaps you can be more specific about what you've tried and what's not working.
