### ISSUE TITLE
The sankey is not shown in Jupyter notebook

### ISSUE THREAD

**Issue by ghost** [ricklupton/ipysankeywidget#12]
Hi!
Since a while I am trying to execute it in Jupyter notebook. Seams that everything works but ... is not displaying a chart. Only white space. I tried to save it as a png but is failing (any file is installed).
I tested it:
1. Windows 10, Chrome, Jupyter version 4.2.0, conda 4.3.21, pip 9.x, ipysankeywidget (installed), and enable. 
2. MacOS, Chrome, and Safari, Jupyter 5x, ipysankeywidget (installed), and enable
In both cases: 
I used ipywidgets==5.2.2, and ipykernel==4.5.0 and ipysankeywidget==0.2.1

What could be a reason that it´s executed but neither displayed nor known?
Thanks!

**Comment by ilaxes** [comment]
I don't know if the problems are related but I had the same problem and running my notebook in Pycharm realised there was a problem with my ipywidgets installation (There was no error showed in Jupyter).
I had multiple ipywidgets files installed in different environments and it messed up jupyter.

**Comment by arnaudmiribel** [comment]
I have the exact same problem. Nothing is displayed (white space)

**Comment by ricklupton** [comment]
Thanks for the reports, I'll see if I can reproduce the problem.

**Comment by ricklupton** [comment]
@ghost I've tried creating new conda environments on OSX using Safari, with the versions you say, both Python 2 and 3, and it works as expected. It's also working on Linux in Chrome and Firefox. Were you testing it in a new installation, or is it possible you have some files from an older version of ipywidgets/ipysankeywidget?

Saving as a png won't work unless the diagram is visible in the notebook -- it's rendered as SVG in the browser first then saved as png.

**Comment by njwhite** [comment]
I hit this too - `pip uninstall`'ing `ipysankeywidget` and `ipywidgets`, then `pip install`ing them and running `jupyter nbextension enable --py --sys-prefix ipysankeywidget` worked!

**Comment by ricklupton** [comment]
@njwhite thanks for the comment. Most problems seem to be to do with not activating the extensions properly (both ipysankeywidget and widgetsnbextension/ipywidgets). I've added a note to the README that hopefully makes this clearer.

**Comment by PedroGFonseca** [comment]
Might be useful to those who are trying to reproduce the tutorial and failing: the source/target pairs must be unique, or it will fail silently and just not plot anything.

**Comment by ricklupton** [comment]
@PedroGFonseca @amandamoran this has been fixed to give an error when this happens (see #23) but I'm afraid I haven't released a new version yet. In the meantime you can install from git master if you'd like the latest version.

@PedroGFonseca the (`source`, `target`, `type`) triplets must be unique -- if you want to have multiple "stripy" flows try setting `type`? You might also find https://github.com/ricklupton/floweaver useful for aggregating and grouping data, setting colours etc in preparing Sankey diagrams.

**Comment by gnfrazier** [comment]
@njwhite this fixed my issue too. Must have missed that portion of the readme when setting up. Thanks!

**Comment by bfmilan** [comment]
Hey! Great code here! I am also tryng to run some code, and always getting the 'Loading widget...' on jupyter lab, but diagram showing on jupyter notebok... (tried Chrome, install, uninstall, Firefox..)
