### ISSUE TITLE
'groups' option from doesn't work

### ISSUE THREAD

**Issue by ilaxes** [ricklupton/ipysankeywidget#13]
It's seems the groups option from d3-sankey-diagram has not been implemented even if it's listed in the advanced examples.

**Comment by ricklupton** [comment]
Thanks for the report, I think this got missed in an update to the underlying d3-sankey-diagram package, I'll take a look.

**Comment by snth** [comment]
I agree. I'm also not seeing the groups when I set them.

**Comment by daronjp** [comment]
I'm running into the same issue as well.

**Comment by ricklupton** [comment]
This is fixed in the latest ipysankeywidget:

http://nbviewer.jupyter.org/github/ricklupton/ipysankeywidget/blob/f91759eb35558f50793f5d4da813a9f49e1922c6/examples/More%20examples.ipynb#Node-groups
