### ISSUE TITLE
Bulk change the values with a slider doesn't work

### ISSUE THREAD

**Issue by dylancsumner** [ricklupton/ipysankeywidget#14]
Hi,

I'm trying to use sankey diagrams alongside some standard matplotlib plots in an interactive jupyter session by using some widgets. I have a function that calculates the necessary values for each link from some input variables, one of which is an int slider. However when I move the slider around the sankey diagram is redrawn for each slider value rather than being dynamically updated. Could you please advise is there a way to fix this or am I doing something wrong.

Many Thanks,

**Comment by ricklupton** [comment]
Hi,

Have you seen the example here?
http://nbviewer.jupyter.org/github/ricklupton/ipysankeywidget/blob/master/examples/Linking%20and%20Layout.ipynb

The demo doesn't work on nbviewer, but you can download the example notebooks and try them locally.

If you're getting multiple copies of the Sankey perhaps you're calling `IPython.display.display()` in the slider callback, or returning the SankeyWidget from `interact()`?

**Comment by ricklupton** [comment]
@dylancsumner did you figure this out? closing this issue but let me know if you think there is something that we can fix in ipysankeywidget.
