### ISSUE TITLE
Is there a way to have different values at the source and target of a link?

### ISSUE THREAD

**Issue by snth** [ricklupton/ipysankeywidget#15]
I have quantities that grow over time so I would like to be able to specify things like:

```
{'source': 'a', 'target': 'b', 'source_value': 1, 'target_value': 2}
```

**Comment by ricklupton** [comment]
I don't think this really fits with the idea of a Sankey diagram, which shows flows of things that are conserved. If you want to show how something has changed over time using a Sankey diagram you can show the increase explicitly:
![image](https://user-images.githubusercontent.com/878794/33281124-12b59cd8-d39c-11e7-990b-86566a85b2f6.png)

```python
links = [
    {'source': 'T = 1', 'target': 'T = 2', 'value': 2},
    {'source': 'Increase', 'target': 'T = 2', 'value': 1},
    {'source': 'T = 2', 'target': 'T = 3', 'value': 3},
]
```

**Comment by snth** [comment]
Ok, that makes sense. Thanks @ricklupton
