### ISSUE TITLE
Error in reproducing simple example

### ISSUE THREAD

**Issue by uipo78** [ricklupton/ipysankeywidget#16]
I tried reproducing [your simple example](http://nbviewer.jupyter.org/github/ricklupton/ipysankeywidget/blob/master/examples/Simple%20example.ipynb) but received the following error:

> TypeError                                 Traceback (most recent call last)
\<ipython-input-24-b42a1aad6fb3\> in \<module\>()
----> 1 w = SankeyWidget(links=links, margins=dict(top=0, bottom=0, left=50, right=100))
TypeError: wrap() got an unexpected keyword argument 'links'

**Comment by uipo78** [comment]
Ok, well, the issue was solved by just restarting the notebook server...............

Sorry for the bother!

**Comment by ricklupton** [comment]
No worries, thanks for reporting it. I've seen this once but it went away and I don't know what causes it...
