### ISSUE TITLE
calling SankeyWidget keeps kernel busy

### ISSUE THREAD

**Issue by dewald-galjaard** [ricklupton/ipysankeywidget#2]
Hi,

I am new to jupyter notebooks, so this problem might be something I'm doing wrong. I've installed the widget and can see it listed and enabled in 'Environment' parameters page using anaconda. I've opened the shared notebook and can import the libraries etc. When I get to calling SankeyWidget (third cell), the kernel is kept busy (I assume this is what is happening seeing I get an asterisk?). Either way, I can't get the diagram to show. 

Could you advise?

Thanks
D

**Comment by ricklupton** [comment]
What version of the notebook are you using?

You could open the developer console in the browser and check if there are any errors reported.

I'm not sure what the Environment parameters page is with anaconda. You can check the nbextension is installed correctly by running `jupyter nbextension list`, which shows this on my computer:
```
Known nbextensions:
  config dir: /home/rick/.jupyter/nbconfig
    notebook section
      jupyter-sankey-widget/extension  enabled 
      - Validating: OK
  config dir: /home/rick/anaconda3/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
```

**Comment by aneverov4vmw** [comment]
Experienced today this on Safari on Mac. Switching to Chrome solved the issue.

**Comment by dewald-galjaard** [comment]
Hi ricklupton,

I'm using 4.2.2.

I tried what aneverov4vmw suggested it's working now. It doesn't seem like this widget runs on Safari (9.1.2).

Thanks for your help!

**Comment by ricklupton** [comment]
Glad it's working now. I'll add a note to the README that it's not working on Safari.

I don't have a Mac to test on at the moment. Did you see anything in the error console that might indicate why it's not working?

**Comment by dewald-galjaard** [comment]
Me too! Thank you.

Unfortunately not. I will be making extensive use of this widget, so when I have a moment I'll try to dig deeper.

**Comment by dewald-galjaard** [comment]
Some feedback. I had to bump my python version down to 2.7 again -- turns out the component is now working in Safari.
