### ISSUE TITLE
Broken Saved PNG 

### ISSUE THREAD

**Issue by tarikaltuncu** [ricklupton/ipysankeywidget#20]
Hi,

I'm running to create multiple sankey diagrams in a for loop and all plots well on jupyter notebook. However, the auto_save_png files sometimes does not look ok. They may be cropped - while colors, etc. (as seen below)

As the png or svg appears sometimes:
![sankey_0_16 639](https://user-images.githubusercontent.com/4439117/35389400-803e6c56-01cf-11e8-92f7-f87fb5e235e0.png)

Expected output and what is being seen on jupyter notebook:
![sankey_3_21 733](https://user-images.githubusercontent.com/4439117/35389338-3fbbd498-01cf-11e8-83cd-4d934d25b289.png)

Do you know if there is a way to overcome this problem?

**Comment by ricklupton** [comment]
Hi,

`auto_save_png` works by setting a timeout (waiting for rendering to finish in the browser) then saving the data to a png file. If for some reason rendering takes longer than expected, it might not have finished yet by the time the png is saved.

If you're displaying them in a loop, the rendering probably can't keep up and some are being saved before they've finished displaying.

Try showing them in two steps: first display them, keeping a reference to the widget. Then in another Jupyter cell, call `widget.save_png('filename.png')` for each widget you want to save.

Hope that helps.
Rick

**Comment by tarikaltuncu** [comment]
hi Rick. 

Thank you for the suggestion. It worked charmly. 

Best,
Tarik
