### ISSUE TITLE
Nodes Vertical Alignment

### ISSUE THREAD

**Issue by tarikaltuncu** [ricklupton/ipysankeywidget#21]
Hi,

I was wondering if it'd be possible in an easy way to implement node sorting function in order to reduce cross links on the diagram as much as possible. Some other tools (e.g. Google Charts) can handle this automatically. 

[Another open sourced visualisation project Raw](https://github.com/densitydesign/raw/blob/fed5f73b831906878a32bddaee98dcc5652f1716/charts/alluvial.js) does it by the code snippet which I copy below:

```
d3.values(nested)
	.forEach(function (d){
    	var y = ( height() - d3.sum(d,function(n){ return n.dy+sankey.nodePadding();}) ) / 2 + sankey.nodePadding()/2;
    	d.sort(function (a,b){
    		if (sortBy() == "automatic") return b.y - a.y;
    		if (sortBy() == "size") return b.dy - a.dy;
    		if (sortBy() == "name") return a.name < b.name ? -1 : a.name > b.name ? 1 : 0;
    	})
    	d.forEach(function (node){
    		node.y = y;
    		y += node.dy +sankey.nodePadding();
    	})
    })
```

I'd like to do this and contribute. I tried, but I don't have a clue about javascript.

**Comment by ricklupton** [comment]
Hi,

Thanks for the suggestion and wanting to contribute! Improving the node sorting to avoid links crossing would be great.

d3-sankey-diagram already tries to reduce crossings using the graphviz/dot layout algorithm, but it's incomplete. I think the best way to get started with improving it would be to find some simple examples that Raw / d3.sankey / Google Charts lay out better than we do. If you'd be interested in doing that, it'd be very helpful (and not involve Javascript at first!)?

By the way the "automatic" sorting mode in the snippet you linked is relying on the d3.sankey sorting, which iteratively sweeps back and forth across the diagram to sort nodes. "size" and "name" could be useful alternatives to have in d3-sankey-diagram but they won't in general reduce the crossings.

**Comment by ricklupton** [comment]
Hi @tarikaltuncu, you said you'd like to contribute to improving this. Just wondered if you're still interested in taking a look?

**Comment by ricklupton** [comment]
Closing this here as any improvements to node ordering / layout will need to be done in d3-sankey-diagram.
