### ISSUE TITLE
Can't create graphic with single source

### ISSUE THREAD

**Issue by mmeendez8** [ricklupton/ipysankeywidget#24]
I have spent a reasonable amount trying to figure out why the widget was not appearing and finally I discover it was crashing due to the fact of using a single source.

You can reproduce the error with:

from ipysankeywidget import SankeyWidget

```
links = [{'source': 'A', 'target': 'R548', 'value': 2},
 {'source': 'A', 'target': 'R141', 'value': 2},
 {'source': 'A', 'target': 'R141', 'value': 2},
 {'source': 'A', 'target': 'R434', 'value': 2}]

w = SankeyWidget(links=links, margins=dict(top=0, bottom=0, left=50, right=100))

```
I might try to find the fix for it, but I am running out of time at this moment!

**Comment by ricklupton** [comment]
Thanks for reporting with the code to reproduce! This has recently been fixed to give an error message (see #23) but I need to release a new version of ipysankeywidget with the change.

In your case if you want to distinguish the two links with the same source and target, you need to set `type` to different values for each.

Alternatively, as I commented in #22, if you want to aggregate your data to sum multiple entries you might want to use https://github.com/ricklupton/floweaver, which handles this as well as lots of other data processing, colours etc before you get to the actual Sankey diagram.
