### ISSUE TITLE
Is there a way to increase figure size?

### ISSUE THREAD

**Issue by mmeendez8** [ricklupton/ipysankeywidget#25]
I am using Chrome together with Jupyter and I am not able to increase the size of the diagram.
I have deduced from here #18 that it must exist some way to do this.
This is what I have tried and it is not working:

`SankeyWidget(links=data.to_dict('records'), width=1000, height=900)
`

**Comment by mmeendez8** [comment]
I am sorry I did not realize about the Layout class :)
I will just leave here the solution anyway:

`from ipywidgets import Layout

layout = Layout(width="1000", height="900")
SankeyWidget(links=data.to_dict('records'),layout=layout)`

**Comment by ricklupton** [comment]
Glad you figured it out, and thanks for posting the solution here! If you have a minute, and would like to contribute, it would be great to add it to the README too so it's easier to find for others: [edit README](https://github.com/ricklupton/ipysankeywidget/edit/master/README.md) :book: 

(just ask if you have any questions about this)
