### ISSUE TITLE
Install using conda

### ISSUE THREAD

**Issue by ricklupton** [ricklupton/ipysankeywidget#28]
If anyone has experience of building conda packages, or wants to give it a try, it would be great if ipysankeywidget could be installed using conda. I think this just involves putting together a conda recipe.

See also https://github.com/ricklupton/floweaver/issues/43

Any questions let me know by replying below or asking in the [chat](https://gitter.im/floweaver/Lobby)!

**Comment by big-cake** [comment]
Hello, I'm interested in doing this. It would be my first open-source contribution though. I'm gonna take a look at what it takes to see if I can do this.

**Comment by ricklupton** [comment]
Great, thanks! Let us know how you get on.

**Comment by ricklupton** [comment]
This is now setup through conda-forge.
