### ISSUE TITLE
Example don't working

### ISSUE THREAD

**Issue by Alex-89** [ricklupton/ipysankeywidget#29]
Hello, 

I tried to run the sript "Simple example" and I get the TypeError:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-10-dda820b7c5a3> in <module>()
      1 
      2 
----> 3 w = SankeyWidget(links=links, margins=dict(top=0, bottom=0, left=50, right=100))

TypeError: wrap() got an unexpected keyword argument 'links'
```

I have anaconda with Python 3.4, it's doesn't work in Spyder and in the qtconsole either.

Is this error known?

Thanks for help and best regards.

**Comment by ricklupton** [comment]
Try restarting the kernel and/or the server, does that help? (See #16)

**Comment by Alex-89** [comment]
Hello,

yes I tried this today again and the error doesn't appear longer. But qt doesn't show the diagramm in the console.

It's appear only the "SankeyWidget" object with the links parameter like so:

```
 w
 SankeyWidget(links=[{'value': 2, 'source': 'start', 'target': 'A'}, {'value': 2, 'source': 'A', 'target': 'B'}…
```

Gives another way to show the figure, like matplotlib with a methode "show"?

Tanks for help.

**Comment by ricklupton** [comment]
Jupyter widgets only work in the Jupyter notebook or Jupyterlab -- they won't work in the qt console

**Comment by Alex-89** [comment]
Also it's not possible showing the result in qt, spyder or any other IDE?

Because the script works well without any error. Gives any possible to save the result as pdf or other format?

By the way I have copy the Scipt in a new jupyter console and there don't appear the result either.

![jupyternotebook](https://user-images.githubusercontent.com/31004084/40717528-f82354f8-640c-11e8-84eb-b516bffabeba.JPG)

**Comment by ricklupton** [comment]
Please can you check you've enabled both the ipysankeywidget and the ipython widgets following the installation instructions? https://github.com/ricklupton/ipysankeywidget#installation

If so and it still doesn't work, please have a look in the browser console and post a picture of any error messages.

**Comment by flyger** [comment]
I was just using ipysankeywidget, got a nice sankey going on ... then moved the exact jupyter notebook to my main machine where stuff was installed exactly the same and got errors. The basic sample put in exactly throws error:

-- ERROR--
TypeError                                 Traceback (most recent call last)
<ipython-input-3-3e5b345bbfdb> in <module>()
     19 
---> 20 w = sw(links=links, margins=dict(top=0,bottom=0,left=50,right=100))
     21 
     22 w

TypeError: wrap() got an unexpected keyword argument 'links'

-------------------
My environment:

Notebook service has been restarted a bunch.

Python 3.5.4 :: Anaconda 2.5.0 (64-bit)

conda list ipython
# packages in environment at D:\Anaconda3:
#
ipython                   6.1.0                    py35_0
ipython-genutils          0.2.0                     <pip>
ipython-notebook          4.0.4                    py35_3
ipython-qtconsole         4.0.1                    py35_4
ipython_genutils          0.2.0                    py35_0

**Comment by ricklupton** [comment]
@flyger thanks for reporting the error. This usually is caused when the notebook server hasn't been restarted since ipysankeywidget was installed, but you said you've restarted already. Are you still seeing this problem?

The package `ipython-notebook 4.0.4 py35_3` looks a bit odd. Are you using the latest version of the notebook, which I think is provided by the package called just `notebook`?

**Comment by flyger** [comment]
Hi Rick, thanks for getting back with me. Indeed -- having some libraries out of date was the issue! I was meaning to comment on that a couple days ago but doing a quick check of my current versions (and updating) was the solution.

**Comment by ricklupton** [comment]
Great, glad it's working now.

**Comment by Talgat2** [comment]
> Also it's not possible showing the result in qt, spyder or any other IDE?
> 
> Because the script works well without any error. Gives any possible to save the result as pdf or other format?
> 
> By the way I have copy the Scipt in a new jupyter console and there don't appear the result either.
> 
> ![jupyternotebook](https://user-images.githubusercontent.com/31004084/40717528-f82354f8-640c-11e8-84eb-b516bffabeba.JPG)

I had the same problem: the code run without any problems, but instead of a graph there was this text "SankeyWidget {links...". The solution was to use the Jupyter Notebook not in Internet Explorer, but in Chrome.

**Comment by ricklupton** [comment]
Can you look in Internet Explorer in the developer console (or equivalent) to see if there are any Javascript errors reported that are causing it not to work?

**Comment by Talgat2** [comment]
![ie_error](https://user-images.githubusercontent.com/43268613/45605907-8ffbb800-ba62-11e8-9e57-0c5cbd8e5371.PNG)
Sure. Here is a screenshot. Is it helpful?

**Comment by Talgat2** [comment]
All the four errors appeared after step 46 (definition of w).

**Comment by ricklupton** [comment]
Those look like generic Jupyter widgets errors (not necessarily to do with ipysankeywidget specifically). Do other ipywidgets work for you?

**Comment by Talgat2** [comment]
You are right, other ipywidgets do not work for me.
