### ISSUE TITLE
Chart fails to display depending on data

### ISSUE THREAD

**Issue by Prabhakar-B** [ricklupton/ipysankeywidget#31]
In the Quickstart tutorial, I tried my own data from our maintenance records. There are 12 records in one file, and this displays without problems. But, when data collected over a few more days are added, as in the second csv file with 16 records, the chart fails to display.
[TwoInputCSVfiles.zip](https://github.com/ricklupton/ipysankeywidget/files/2194986/TwoInputCSVfiles.zip)

**Comment by Prabhakar-B** [comment]
By the way, the error in the Firefox web console when the chart fails to display is:
Error: "Could not create a view for model id e2efed7db45349c39466dcc5bbf5679c"
promiseRejectionhttp://localhost:8888/nbextensions/jupyter-js-widgets/extension.js?v=20180716023713:21583:27 utils.js:119
Error: "Could not create view"
promiseRejectionhttp://localhost:8888/nbextensions/jupyter-js-widgets/extension.js?v=20180716023713:21583:27

**Comment by Prabhakar-B** [comment]
Further investigation revealed that the problem occurs when source, target, and type were duplicated in different records, as would happen in maintenance activities -- the work is done on the same machine over time. So, the work around was a groupby:
flows = (flows.groupby([flows.source,flows.target,flows.type]).sum()).reset_index()
The above line added to the code to sum those duplicate records solves the problem.

Thanks for a really great tool!

**Comment by ricklupton** [comment]
Hi, glad you figured it out! There's a fix (#23) to give a better error message when this happens but I still need to release the new version.

You might want to look also at [floWeaver](https://github.com/ricklupton/floweaver), which gives a flexible framework for doing exactly the kind of grouping and aggregation that you found as a solution. See also [this comment](https://github.com/ricklupton/ipysankeywidget/issues/12#issuecomment-383315530).

Glad you're finding it useful! If you're able to share, could you explain a little more about what kind of maintenance records your data are and what you're using it for -- it's always interesting to see what people are using it for!

**Comment by Prabhakar-B** [comment]
floWeaver looks more complicated, but will surely look at it for more complex needs that are still in the planning stage.

In our plant we have hundreds of machines with a number of maintenance activities with different schedules. It becomes difficult to visualize the kind of activities that are pending, on different machines without a tool like this. If the maintenance work orders captured in a database, this tool can be very helpful to analyze. I have been able to look at the activities by types of machines over a year to quickly identify machines with repeated problems, and schedules that were missed.

**Comment by Prabhakar-B** [comment]
Just to be clear:
source = maintenance activity (code)
target = Machine
Type = Description, or could be some grouping such as Expensive, Needing Manpower, Long down-time, etc.
value = man-hours or cost

Hope someone finds this useful like I did!

Thanks again!

**Comment by ricklupton** [comment]
Sounds good, thanks for explaining :)
