### ISSUE TITLE
Disable printing of nodeTitle 

### ISSUE THREAD

**Issue by Mofef** [ricklupton/ipysankeywidget#35]
Hey, thanks for your work :)

Since I have pretty long node titles/names/ids I would like to disable the display of those and purely rely on the tooltips to identify nodes.

Is there an easy way to do that?

Thanks a lot!

**Comment by ricklupton** [comment]
Hi, sorry for the slow reply. Probably using a custom CSS stylesheet would be the best way to do this -- see the example [here, cell 13](http://nbviewer.jupyter.org/github/ricklupton/ipysankeywidget/blob/master/examples/More%20examples.ipynb#Styling).

This seems to work:
```ipython
%%html
<style>
.sankey .node text {
    visibility: hidden;
}
</style>
```

**Comment by ricklupton** [comment]
Let me know if that solves it for you, or if there's some more specific feature that would be useful.

**Comment by Mofef** [comment]
Hey, thanks a lot! 
I was just searching for something like this again and was quite surprised to find my own issue and even your answer. I must have missed it somehow.... :man_facepalming: 
So, yes thanks that works for me! :)

**Comment by ricklupton** [comment]
Glad to hear it!
