### ISSUE TITLE
"Error displaying widget" in Jupyterlab

### ISSUE THREAD

**Issue by gsemet** [ricklupton/ipysankeywidget#36]
Hi

I can get `ipysankeywidget` working in jupyter (on jupyterhub), but it fails when the notebook is opened with jupyterlab. Here the error:
```
Error displaying widget
```

The console shows a bit more information:
![error-ipysankey](https://user-images.githubusercontent.com/133498/47363978-688ab180-d6d8-11e8-9ecc-b974f5251cb4.png)

Any idea on how to install it on jupyterlab? jupyterlab-manager is well installed, plotly and other ipywidget extension work fine. I can't get ipysankey to load `jupyter-sankey-widget`.

Thanks

**Comment by ricklupton** [comment]
Hi, thanks for reporting this! I believe jupyterlab uses a slightly different widget extension system so ipysankeywidget needs to be updated before it will work there. 

I’d like to get this to work at some point whenever we have time to work on it. If you know any more about this or would like to do some research that’d be very helpful to get the ball rolling. 

Thanks

**Comment by gsemet** [comment]
indeed the plugin should be ported to jlab

**Comment by ami-navon** [comment]
+1

**Comment by anki-code** [comment]
+1

**Comment by ricklupton** [comment]
Version 0.3.0 now supports jupyterlab!
