### ISSUE TITLE
Compatibility with Jupyter Lab 

### ISSUE THREAD

**Issue by ZachEd96** [ricklupton/ipysankeywidget#37]
Is there any chance of updating this to make it work with Jupyter Labs? It's a bit tedious to constantly swap between the Lab and Notebook interfaces to see outputs.

**Comment by ricklupton** [comment]
Thanks, I think this is a duplicate of #36

**Comment by ZachEd96** [comment]
Oh yeah! Apologies I did take a look before I posted but must have missed it.

Will close this issue now :)
