### ISSUE TITLE
[Feature Request] Can I use this to create behavior flow chart?

### ISSUE THREAD

**Issue by mingchau** [ricklupton/ipysankeywidget#38]
Hi @ricklupton : 

Thanks for your contribution!
Related to what I'm working on(users behaviors flow visualization), the data-set like:

		step1	step2	step3
	user1	A	B	C
	user2	B	C	A
	user3	C	B	bounce out
	user4	C	A	C

Can I use the ipysankeywidget to create a flow chart like the attached picture?
![behavior_flow_report_from_google_analytics](https://user-images.githubusercontent.com/18564039/48125370-7ab04680-e2b9-11e8-8420-2f116dced651.png)

Wish to hear from you soon!

**Comment by ricklupton** [comment]
Hi @mingchau, sorry for the slow reply. Yes you should be able to use ipysankeywidget to create that. You just need to expand your dataset into a list of flows like this:

```
source	target	value
step1-A	step2-B	10
step2-B	step3-C	10
step1-C	step2-B	3
step2-B	step3-bounce	2
step2-B	step3-other	1
```

and so on. Where the first two rows are roughly your `user1` row and the final 3 rows are roughly your `user3` (split to show how you'd do that).

You can add a `type` column to distinguish different types of users using different colours too.

**Comment by mingchau** [comment]
Thank you for your response, yes I already output a nice behavior flow graph. Wait for the new label feature now :)
