### ISSUE TITLE
Changing font size and style

### ISSUE THREAD

**Issue by hakanjonsson** [ricklupton/ipysankeywidget#4]
I am trying to use the ipysankeywidget, and it works fine, but I can't find a way to change the font size of node titles. I don't know much Javascript, so the line in the readme "the value of the SankeyWidget is exactly the same as the sankey object described there" unfortunately doesn't help me very much. I have tried setting things by accessing the sankey object like this:
`nbsankeyExample.font_style = 'italic'`
`nbsankeyExample.font_style`
`u'italic'`
, and it returns the value correctly, but when showing the widget again, the value is not used.

**Comment by hakanjonsson** [comment]
Found it (the styling part of the docs). Works fine now.

**Comment by ricklupton** [comment]
Thanks for raising this. When I tried doing `nbsankeyExample.font_style = 'italic'`, it did nothing, as you said. How did you get it to work?

I normally adjust the styling in the notebook using CSS:
```ipython
%%html
<style>
.sankey .node {
    font-style: italic;
}
</style>
```

Do you mean these styling docs?
http://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Styling.html

**Comment by hakanjonsson** [comment]
I was referring to this: https://github.com/ricklupton/ipysankeywidget/blob/7762bdd6981a53cace697d9d4a2e1cb5fc0e135f/examples/More%20examples.ipynb, but it did not help with the italics or font_size. I think I was thinking about node titles when I said it helped. Thanks for the tip on using CSS.
