### ISSUE TITLE
Long labels of source and target gets cut off :'(

### ISSUE THREAD

**Issue by cuddle-cuddle** [ricklupton/ipysankeywidget#40]
Long labels gets cut off. 
Sometimes I need long labels. 
I've been trying to get it to work all weekend. :'(

Thank you very much for helping!

for example, the image is produced by: 
![cutoff_example](https://user-images.githubusercontent.com/34894274/54482144-33ad0180-4815-11e9-88af-f34473875053.png)

`layout = Layout( width="600", height="600",
                #margins=dict(left=300, right=300, top=50, bottom=50),
                #paddings=dict(left=300, right=300, top=50, bottom=50),
                flex_flow='row wrap', overflow = 'visible',
                border='1px solid black',
                grid_auto_flow='row',
                display='block'
               )
flows = pd.read_csv('simple_fruit_sales.csv')
flows['source'] = flows['source'].apply(lambda x:  x + "\nblahblah\n100000\n")
flows['target'] = flows['target'].apply(lambda x:  x + " derpy derp derp")
w = SankeyWidget(links=flows.to_dict('records'), layout=layout)
w `

**Comment by cuddle-cuddle** [comment]
code: 

layout = Layout( width="600", height="600",
                #margins=dict(left=300, right=300, top=50, bottom=50),
                #paddings=dict(left=300, right=300, top=50, bottom=50),
                flex_flow='row wrap', overflow = 'visible',
                border='1px solid black',
                grid_auto_flow='row',
                display='block'
               )
flows = pd.read_csv('simple_fruit_sales.csv')
flows['source'] = flows['source'].apply(lambda x:  x + "\nblahblah\n100000\n")
flows['target'] = flows['target'].apply(lambda x:  x + " derpy derp derp")
w = SankeyWidget(links=flows.to_dict('records'), layout=layout)
w

**Comment by ricklupton** [comment]
Try this:

```
w = SankeyWidget(links=links, margins=dict(top=0, bottom=0, left=50, right=100))
```

From here: https://nbviewer.jupyter.org/github/ricklupton/ipysankeywidget/blob/master/examples/Simple%20example.ipynb

**Comment by ricklupton** [comment]
Closing this now assuming that worked.
