### ISSUE TITLE
Google Colab

### ISSUE THREAD

**Issue by ajoorabchi** [ricklupton/ipysankeywidget#42]
Just wondering if anybody has managed to get this widget to run in Google Colab? I don't get any error but the chart does not display
![image](https://user-images.githubusercontent.com/4104802/59191139-955fdc00-8b76-11e9-9c3a-647f98c390e5.png)

![image](https://user-images.githubusercontent.com/4104802/59191051-4f0a7d00-8b76-11e9-9d87-0120671ebe3c.png)

**Comment by ricklupton** [comment]
Hi, sorry for the slow reply -- I've never used Google Colab so I don't know for sure. But it looks like they have a completely separate widget system so it wouldn't automatically work. Probably the d3-sankey-diagram library could be wrapped in a Colab-widget.
