### ISSUE TITLE
render image from ipython (not jupyter notebook)

### ISSUE THREAD

**Issue by alexbovet** [ricklupton/ipysankeywidget#46]
Hi, 

I would like to use ipysankeywidget from an IPython terminal (from spyder actually) to generate Sankey diagram. 
If I try the [simple example](https://nbviewer.jupyter.org/github/ricklupton/ipysankeywidget/blob/master/examples/Simple%20example.ipynb), I can do everything without any error but nothing is displayed.

Is it possible to output the result in a html or svg file from an IPython terminal? I didn't find anything in the documentation.

Thanks for this great project!

**Comment by ricklupton** [comment]
Hi,

ipysankeywidget only works within Jupyter Notebook or Jupyter Lab. If you want to create Sankey diagrams outside of that, try saving the data as a JSON file and using [svg-sankey](https://github.com/ricklupton/svg-sankey) which uses the same underlying library for doing the rendering -- does that do what you're looking for?

**Comment by alexbovet** [comment]
Thanks! Using .to_json() from a SankeyData created from weave does the trick.
