### ISSUE TITLE
jupyterlab error displaying widget

### ISSUE THREAD

**Issue by mfastudillo** [ricklupton/ipysankeywidget#48]
Hello

I was using ipsankeywidget with jupyter notebooks but I've recently (today) reinstalled it and was hoping to be able to use on jupyter lab with the new support. 

However I am getting an error: `Error displaying widget: model not found` even with very simple diagrams. the extensions seem to be correctly installed. 

![imagen](https://user-images.githubusercontent.com/11621547/73366144-b9ab2d00-42ad-11ea-9905-02ae0b32c61f.png)

If I try to run the same notebook using the classic notebook I don't get the same error but there is no rendered image.

thanks!

**Comment by mfastudillo** [comment]
I think the problem is that I installed it using conda, and the pip version has been updated to 0.3, while the one in conda-forge is still the version 0.25

![imagen](https://user-images.githubusercontent.com/11621547/73436724-5a9bf580-434b-11ea-9d37-00015e46bdc2.png)

**Comment by ricklupton** [comment]
Thanks for spotting that, I’ll check the conda forge version gets updated. 

Is version 0.3 working ok for you in jupyter lab?

**Comment by mfastudillo** [comment]
yes, version 0.3 works fine in jupyter lab as far as I can tell.

**Comment by KommandorKeen** [comment]
I have the same trouble, but have the following installed. Works PERFECTLY in notebook, but delivers ' Error displaying widget: model not found' 
Any pointers?
ipysankeywidget           0.3.0                      py_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            6.1.3                      py_0    conda-forge
jupyter_console           6.1.0                      py_1    conda-forge
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_contrib_nbextensions 0.5.1                    py37_0    conda-forge
jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
jupyter_highlight_selected_word 0.2.0                 py37_1000    conda-forge
jupyter_latex_envs        1.4.4                 py37_1000    conda-forge
jupyter_nbextensions_configurator 0.4.1                    py37_0    conda-forge
jupyterlab                2.1.1                      py_0    conda-forge
jupyterlab_server         1.1.1                      py_0    conda-forge
