### ISSUE TITLE
JupyterLab error displaying widget (Chrome, MacOS)

### ISSUE THREAD

**Issue by mikerob-w4** [ricklupton/ipysankeywidget#49]
Hi,

I followed conda installation instructions for ipysankeywidget and then tried the simple example code but found that a widget did not display using JupyterLab (2.0.1) but did display using Jupyter Notebook.

This is on same computer (MacOS 10.15.4) and same browser (Chrome).

Anaconda Navigator is showing ipsankeywidget 0.3.0 installed and jiupyter-sankey-widget appears in the JupyterLab extension manager.

Chrome developer console shows the following error when executing the layout = Layout(width="500", height="200") line of code.

Executing the sankey command in simple example shows the sankey object but no diagram. 
[localhost-1585306478218.log](https://github.com/ricklupton/ipysankeywidget/files/4392932/localhost-1585306478218.log)

**Comment by MSeal** [comment]
In jupyter classic I also see this in the console:

```
```
Failed to load resource: the server responded with a status of 404 (Not Found)
manager-base.js:273 Could not instantiate widget
(anonymous) @ manager-base.js:273
2require.js?v=951f856e81496aaeec2e71a1c2c0d51f:168 Uncaught (in promise) Error: Script error for "jupyter-sankey-widget"
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js?v=951f856e81496aaeec2e71a1c2c0d51f:168)
    at HTMLScriptElement.onScriptError (require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1735)
DevTools failed to parse SourceMap: http://localhost:8889/static/components/preact/preact.min.js.map
DevTools failed to parse SourceMap: http://localhost:8889/static/components/proptypes/index.js.map
DevTools failed to parse SourceMap: http://localhost:8889/static/components/preact-compat/preact-compat.min.js.map
Untitled2.ipynb?kernel_name=python3:1 Uncaught (in promise) Error: Script error for "jupyter-sankey-widget"
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js?v=951f856e81496aaeec2e71a1c2c0d51f:168)
    at HTMLScriptElement.onScriptError (require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1735)
```

**Comment by spica155** [comment]
I've a similar issue: Just installed ipysankeywidget and tried to follow the simple example. However, I cannot get the widget to display. Running MacOS 10.15.6 and tired it with 
- Jupyter Notebook (6.0.3) with Python 3.7.7 in Firefox (79.0.2)
- Jupyter Lab (2.2.2) with Python 3.8.5 in Firefox
- Jupyter Lab with Python 3.8.5 in Chrome (84.0.4147.105)

None of them work. One combination that actually displays the widget is
- Jupyter Notebook, Python 3.7 in Chrome

Didn't try other possible permutations.

**Comment by ricklupton** [comment]
Closing as the jupyter widget code has been updated since then. Please comment if this is still an issue.
