### ISSUE TITLE
Link Titles

### ISSUE THREAD

**Issue by hakanjonsson** [ricklupton/ipysankeywidget#5]
How do I set the link titles? I want to show the link values, preferably on the links, but I can't find a way to do it. Currently I am instead setting the node titles as the values of the links, but it does not look good. In general, how do I access the link appearance functions of d3-sankey-diagram diagram object?

**Comment by ricklupton** [comment]
Thanks for posting this here!

Currently there's no support for displaying link values on the links as text, I'm afraid. The values should appear as tooltips when you hover over the link, but that doesn't help if you want a static image.

I might add this at some point, or contributions are welcome -- it would have to be added [here](https://github.com/ricklupton/d3-sankey-diagram/blob/master/src/link.js#L13-L36) somewhere.

**Comment by ricklupton** [comment]
Needs to be implemented in d3-sankey-diagram, so I've added an issue there: ricklupton/d3-sankey-diagram#2
