### ISSUE TITLE
Does not display in Google Colab notebooks

### ISSUE THREAD

**Issue by zacstewart** [ricklupton/ipysankeywidget#52]
It took a little hacking around to get it to install and enable the extension, and I'm still not sure if I got that right, but it seems to work. That is until you try to display the widget. It's blank. Furthermore, if you access the `.png` property, it is empty.

Check out [my notebook](https://colab.research.google.com/drive/1VOMIbkT0Dplac9YFq4rc46hiJeyJfXx0?usp=sharing)

**Comment by ricklupton** [comment]
Hi, I've not used Google Colab so I'm not sure about the installation issues.

In your notebook you seem to have an error importing `Layout` which is presumably preventing it from working? See the example here that it should be imported from `ipywidgets`:
https://nbviewer.jupyter.org/github/ricklupton/ipysankeywidget/blob/master/examples/More%20examples.ipynb

**Comment by zacstewart** [comment]
Ah. I was fooling around with the Layout bit and left that error there. I've removed it, and still you can see that `.png` and `.svg` are `''`'. 

https://colab.research.google.com/drive/1VOMIbkT0Dplac9YFq4rc46hiJeyJfXx0?usp=sharing

**Comment by ricklupton** [comment]
Closing as the jupyter widget code has been updated since then. Please comment if this is still an issue.
