### ISSUE TITLE
Updates needed for latest ipywidgets

### ISSUE THREAD

**Issue by ricklupton** [ricklupton/ipysankeywidget#53]
See
- https://github.com/jupyter-widgets/ipyleaflet/issues/396
- https://github.com/jupyter-widgets/ipywidgets/issues/2470

Possible fixes:
- https://github.com/jupyter-widgets/ipyleaflet/commit/45f0f512d814c893f121166c49088dad5a2add3f
- https://github.com/jupyter-widgets/ipyleaflet/commit/a2c383d73884bf2f05f7ef4987248876171d993b

May be related to issues #52 and #48 and #47

**Comment by ricklupton** [comment]
Downgrading to ipywidgets==7.4.2 and notebook==5.7.8 works in the meantime

**Comment by xiaoshir** [comment]
Hi, I installed this package but the diagram can not be shown. I'm using Jupyter Notebook and Chrome. Below are my packages and their versions in the env I'm working on. I have already downgrade ipywidgets==7.4.2, as you suggested here. But it is still not displaying. 

# packages in environment at C:\miniconda3_py37\envs\impega:
#
# Name                    Version                   Build  Channel
appdirs                   1.4.3                      py_1    conda-forge
asteval                   0.9.16             pyh5ca1d4c_0    conda-forge
astunparse                1.6.2                      py_0    conda-forge
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
blas                      1.0                         mkl
bleach                    3.1.0                      py_0    conda-forge
brightway2                2.3                        py_2    cmutel
bw2analyzer               0.9.4                      py_1    cmutel
bw2calc                   1.7.8                      py_0    cmutel
bw2data                   3.6.2                      py_0    cmutel
bw2io                     0.7.11.3                   py_0    cmutel
bw2parameters             0.6.6                      py_0    cmutel
bw_migrations             0.1                        py_0    cmutel
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py36_0    conda-forge
cffi                      1.13.2           py36hb32ad35_0    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
click                     7.0                        py_0    conda-forge
colorama                  0.4.3                      py_0    conda-forge
cryptography              2.8              py36hb32ad35_1    conda-forge
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.1                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
docopt                    0.6.2                      py_1    conda-forge
eight                     0.4.2                      py_2    conda-forge
entrypoints               0.3                   py36_1000    conda-forge
fasteners                 0.14.1                     py_3    conda-forge
flask                     1.1.1                      py_1    conda-forge
freetype                  2.10.0               h563cfd7_1    conda-forge
future                    0.18.2                   py36_0    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       64.2                 he025d50_1    conda-forge
idna                      2.8                   py36_1000    conda-forge
importlib_metadata        1.4.0                    py36_0    conda-forge
inflect                   4.0.0                    py36_1    conda-forge
ipykernel                 5.1.4            py36h5ca1d4c_0    conda-forge
ipysankeywidget           0.3.0                    pypi_0    pypi
ipython                   7.11.1           py36h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                    pypi_0    pypi
itsdangerous              1.1.0                      py_0    conda-forge
jaraco.itertools          5.0.0                      py_0    conda-forge
jedi                      0.16.0                   py36_0    conda-forge
jinja2                    2.10.3                     py_0    conda-forge
jpeg                      9c                hfa6e2cd_1001    conda-forge
jsonschema                3.2.0                    py36_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            5.3.4                    py36_1    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.6.1                    py36_0    conda-forge
kiwisolver                1.1.0            py36he980bc4_0    conda-forge
klausen                   0.1.1                    pypi_0    pypi
libblas                   3.8.0                     8_mkl    conda-forge
libcblas                  3.8.0                     8_mkl    conda-forge
libclang                  9.0.1           default_hf44288c_0    conda-forge
libiconv                  1.15              hfa6e2cd_1005    conda-forge
liblapack                 3.8.0                     8_mkl    conda-forge
libpng                    1.6.37               h7602738_0    conda-forge
libsodium                 1.0.17               h2fa13f4_0    conda-forge
libxml2                   2.9.10               h9ce36c8_0    conda-forge
libxslt                   1.1.33               heafd4d3_0    conda-forge
llvm-openmp               9.0.1                         2    conda-forge
lxml                      4.4.2            py36heafd4d3_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.1.1            py36hfa6e2cd_0    conda-forge
matplotlib                3.1.2                    py36_1    conda-forge
matplotlib-base           3.1.2            py36h2981e6d_1    conda-forge
mistune                   0.8.4           py36hfa6e2cd_1000    conda-forge
mkl                       2019.5                      281    conda-forge
mkl-service               2.3.0            py36hfa6e2cd_0    conda-forge
monotonic                 1.5                        py_0    conda-forge
more-itertools            8.1.0                      py_0    conda-forge
mrio_common_metadata      0.1.1                      py_0    cmutel
msys2-conda-epoch         20160418                      1
nbconvert                 5.6.1                    py36_0    conda-forge
nbformat                  5.0.4                      py_0    conda-forge
notebook                  6.0.3                    py36_0    conda-forge
numpy                     1.17.5           py36hc71023c_0    conda-forge
openssl                   1.1.1d               hfa6e2cd_0    conda-forge
pandas                    0.25.3           py36he350917_0    conda-forge
pandoc                    2.9.1.1                       0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.6.0                      py_0    conda-forge
peewee                    3.10.0           py36ha85dd04_0    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pip                       20.0.2                   py36_0
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.10                     py_0    conda-forge
psutil                    5.6.7            py36hfa6e2cd_0    conda-forge
pycparser                 2.19                     py36_1    conda-forge
pygments                  2.5.2                      py_0    conda-forge
pyopenssl                 19.1.0                   py36_0    conda-forge
pypardiso                 0.2.2                      py_0    haasad
pyparsing                 2.4.6                      py_0    conda-forge
pyprind                   2.11.2                py36_1000    conda-forge
pyqt                      5.12.3           py36h6538335_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.15.7           py36hfa6e2cd_0    conda-forge
pysocks                   1.7.1                    py36_0    conda-forge
python                    3.6.10               h9f7ef89_0
python-dateutil           2.8.1                      py_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
pywin32                   225              py36hfa6e2cd_0    conda-forge
pywinpty                  0.5.7                    py36_0    conda-forge
pyzmq                     18.1.1           py36h16f9016_0    conda-forge
qt                        5.12.5               h7ef1ec2_0    conda-forge
qtconsole                 4.6.0                      py_0    conda-forge
requests                  2.22.0                   py36_1    conda-forge
scipy                     1.3.2            py36h29ff71c_0
send2trash                1.5.0                      py_0    conda-forge
setuptools                45.1.0                   py36_0
six                       1.14.0                   py36_0    conda-forge
sqlite                    3.30.1               he774522_0
stats_arrays              0.6.3                      py_0    cmutel
terminado                 0.8.3                    py36_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tornado                   6.0.3            py36hfa6e2cd_0    conda-forge
traitlets                 4.3.3                    py36_0    conda-forge
unicodecsv                0.14.1                     py_1    conda-forge
unidecode                 1.1.1                      py_0    conda-forge
urllib3                   1.25.7                   py36_0    conda-forge
vc                        14.1                 h0510ff6_4
voluptuous                0.11.7                     py_0    conda-forge
vs2015_runtime            14.16.27012          hf0eaf9b_1
wcwidth                   0.1.8                      py_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  0.16.1                     py_0    conda-forge
wheel                     0.33.6                   py36_0
whoosh                    2.7.4                      py_1    conda-forge
widgetsnbextension        3.4.2                    pypi_0    pypi
win_inet_pton             1.1.0                    py36_0    conda-forge
wincertstore              0.2              py36h7fe50ca_0
winpty                    0.4.3                         4    conda-forge
wrapt                     1.11.2           py36hfa6e2cd_0    conda-forge
xlrd                      1.2.0                      py_0    conda-forge
xlsxwriter                1.2.7                      py_0    conda-forge
zeromq                    4.3.2                h6538335_2    conda-forge
zipp                      2.1.0                      py_0    conda-forge
zlib                      1.2.11            h2fa13f4_1006    conda-forge

Which exact package do you mean by "notebook"?
Nothing is displaying when I run it on Binder too. What could be the issue?
![image](https://user-images.githubusercontent.com/28433916/90002858-8b160200-dc93-11ea-8df6-5d00dea47cc1.png)

**Comment by jbaars2** [comment]
@xiaoshir It seems like you are using JupyterLab, try using Jupyter Notebook, that worked for me.

**Comment by ricklupton** [comment]
Closing as the jupyter widget code has been updated since then -- I think this is now supported.
