### ISSUE TITLE
install problem on linux jupyterlab

### ISSUE THREAD

**Issue by Krisselack** [ricklupton/ipysankeywidget#58]
I am not able to install the widget on a jupyter-lap platform on Ubuntu 18.04. 

When running this code
`jupyter labextension install jupyter-sankey-widget`

I get the following error: 
> error fs-events@2.3.2: The platform "linux" is incompatible with this module.

**Comment by pjsmyth** [comment]
Also happens on windows, which makes sense because fs-events appears to be macOS specific.

**Comment by ricklupton** [comment]
Thanks for reporting the issue. I believe some changes may be needed for the newer version of jupyterlab.

**Comment by ricklupton** [comment]
Closing as the jupyter widget code has been updated since then. Please comment if this is still an issue.
