### ISSUE TITLE
Not plotting anymore

### ISSUE THREAD

**Issue by amilovanoff** [ricklupton/ipysankeywidget#59]
Hello,

I have been using the package for couple of years and it does not work anymore. When I run my old scripts in Jupyter Notebook, I don't see anything. I have installed Jupyter lab and it does not work. I have update the package using the conda line, and updated Jupyter too. Still not working! The codes run fine, the SankeyWidget object is created without error. But I just cannot plot it. Thanks for the help. I have python 3.6.12, ipysankeywidget 0.4.0, ipython 7.12.0, jupyter-notebook 6.2.0.

**Comment by ricklupton** [comment]
Closing as the jupyter widget code has been updated since then. Please comment if this is still an issue.
