### ISSUE TITLE
exporting SVG

### ISSUE THREAD

**Issue by hakanjonsson** [ricklupton/ipysankeywidget#6]
I tried exporting a diagram to SVG and png as in the example. The png works fine. If I right-click the pngimage in my notebook, I can save it. If I try the same for the svg image, I can only save the whole notebook, not the svg image. When I try the same from the example html notebook on your github, I can save the SVG. I tried to find a way to programmatically save the svg, but failed to find one.

**Comment by ricklupton** [comment]
I've added more examples to the [notebook](https://github.com/ricklupton/ipysankeywidget/blob/master/examples/Exporting%20Images.ipynb).

You can save svg and png using the `save_svg` and `save_png` methods, but as explained in the notebook, you may want to use `auto_save_svg` and `auto_save_png` instead.

Hope that helps, let us know if not.
