### ISSUE TITLE
Changing color scheme

### ISSUE THREAD

**Issue by timsainb** [ricklupton/ipysankeywidget#7]
Is there anyway to change the color scheme? I can see you're using d3.scale.category20() in the javascript

Can I replace this palette with, say, an seaborn palette?  Thanks!

**Comment by ricklupton** [comment]
You can set the colour from Python by setting the `color` attribute of the links ([code](https://github.com/ricklupton/ipysankeywidget/blob/master/js/src/sankey-widget.js#L53)).

I've added an example of this to the [More examples](https://github.com/ricklupton/ipysankeywidget/blob/master/examples/More%20examples.ipynb) notebook.

Hope that helps, let us know if not.
