### ISSUE TITLE
graph stops drawing sometimes

### ISSUE THREAD

**Issue by dcsan** [ricklupton/ipysankeywidget#72]
I'm often working with a sankey and sometimes it will just refuse to draw:

![image](https://user-images.githubusercontent.com/514002/136138690-9e87f6fd-d6f4-49f6-b098-d1ed28242302.png)

i can mess around with the params and eventually it will draw again - eg with 21 connections instead of 20. It seems to somehow give the renderer a kick.

This looks to me like the CSS isn't loading or something? I can only guess there's some loading order issue to the widget? Are you doing a server-side render of the whole D3 graph?

In this case when I save a png it also comes out the same.

**Comment by ricklupton** [comment]
Is it possible there is a NaN or other funny value in your data for the flow that is causing the problem when you add it back in?

**Comment by aluchuk** [comment]
I'm also getting the same error. 
here is my code:
```
import os
import pathlib
import pandas as pd

import floweaver as fw
from ipysankeywidget import SankeyWidget

os.chdir(os.getcwd())

PATH_DATA = pathlib.Path(r'./storage/shared/Documents')
PATH_RESULTS = pathlib.Path(r'./storage/shared/Documents')

if not PATH_DATA.exists():
    raise ValueError("Data directory not found.")

df = pd.read_csv(PATH_DATA/'flow.csv', low_memory=False)

source_set = set(df['source'])
target_set = set(df['target'])
trunk = source_set - target_set
leaves = target_set - source_set
branches = (source_set | target_set) - trunk - leaves

SankeyWidget(links=df.to_dict('records')).auto_save_png(filename=str(PATH_RESULTS/'sankey_simple.png'))
```

the csv file:
```
source,AMOUNT,target
wages,75000,income
interest,30,income
other,5000,income

income,5,expenses
income,6000,liabilities
income,300,loans
income,200,savings

expenses,1000,Education
expenses,1999,Insurance
expenses,123,Medical
expenses,240,utilities

liabilities,745,Chase
liabilities,137,Discover

loans,2500,Education
loans,17000,Mortgage
loans,6000,Car
```

and the result 
![sankey_simple](https://user-images.githubusercontent.com/415877/222753838-be3d00ff-c483-40ae-9ae8-56a34b5b3eff.png)
