### ISSUE TITLE
Extension Enable issue during sankey install

### ISSUE THREAD

**Issue by jgiegel** [ricklupton/ipysankeywidget#75]
@ricklupton any insight?  Seem to have any issue with the extension for the sankey widget.  Tried the standard install protocols, multiple times.

$ jupyter nbextension list
Known nbextensions:
  config dir: /Users/-/opt/anaconda3/etc/jupyter/nbconfig
    notebook section
      ipysankeywidget/extension  enabled 
      - Validating: problems found:
        - require?  X ipysankeywidget/extension
      jupyterlab-plotly/extension  enabled 
      - Validating: OK
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
      jupyter-sankey-widget/extension  enabled 
      - Validating: OK

**Comment by ricklupton** [comment]
Thanks for reporting. I've updated the widget structure in #84 and I think this should be fixed.
