### ISSUE TITLE
The 'kernel' trait of a Comm instance must be a Kernel, but a value of class 'NoneType' (i.e. None) was specified.

### ISSUE THREAD

**Issue by chananshgong** [ricklupton/ipysankeywidget#8]
In [1]: from ipysankeywidget import SankeyWidget
   ...:

In [2]: links = [
   ...:     {'source': 'start', 'target': 'A', 'value': 2},
   ...:     {'source': 'A', 'target': 'B', 'value': 2},
   ...:     {'source': 'B', 'target': 'start', 'value': 0.2},
   ...:     {'source': 'C', 'target': 'A', 'value': 2},
   ...:     {'source': 'A', 'target': 'C', 'value': 2},
   ...: ]
   ...:

In [3]: nbsankeyExample = SankeyWidget(value={'links': links}, width=400, height=200,
   ...:                                margins=dict(top=0, bottom=0))
   ...:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
C:\Users\username\Anaconda3\lib\site-packages\traitlets\traitlets.py in get(self, obj, cls)
    525         try:
--> 526             value = obj._trait_values[self.name]
    527         except KeyError:

KeyError: 'layout'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
C:\Users\username\Anaconda3\lib\site-packages\traitlets\traitlets.py in get(self, obj, cls)
    525         try:
--> 526             value = obj._trait_values[self.name]
    527         except KeyError:

KeyError: 'kernel'

During handling of the above exception, another exception occurred:

TraitError                                Traceback (most recent call last)
<ipython-input-3-c36f52a0e5ef> in <module>()
      1 nbsankeyExample = SankeyWidget(value={'links': links}, width=400, height=200,
----> 2                                margins=dict(top=0, bottom=0))

C:\Users\username\Anaconda3\lib\site-packages\ipysankeywidget\sankey_widget.py in __init__(self, **kwargs)
     28     def __init__(self, **kwargs):
     29         """Constructor"""
---> 30         super(SankeyWidget, self).__init__(**kwargs)
     31         self._selected_handlers = widgets.CallbackDispatcher()
     32         self._auto_png_filename = None

C:\Users\username\Anaconda3\lib\site-packages\ipywidgets\widgets\domwidget.py in __init__(self, *pargs, **kwargs)
     88
     89     def __init__(self, *pargs, **kwargs):
---> 90         super(DOMWidget, self).__init__(*pargs, **kwargs)
     91
     92         # Deprecation added in 5.0.  TODO: Remove me and corresponging traits.

C:\Users\username\Anaconda3\lib\site-packages\ipywidgets\widgets\widget.py in __init__(self, **kwargs)
    179         """Public constructor"""
    180         self._model_id = kwargs.pop('model_id', None)
--> 181         super(Widget, self).__init__(**kwargs)
    182
    183         Widget._call_widget_constructed(self)

C:\Users\username\Anaconda3\lib\site-packages\traitlets\config\configurable.py in __init__(self, **kwargs)
     91         # explicitly assigned values.
     92         for key, value in kwargs.items():
---> 93             setattr(self, key, value)
     94
     95     #-------------------------------------------------------------------------

C:\Users\username\Anaconda3\lib\site-packages\ipywidgets\widgets\domwidget.py in width(self, value)
     32     @width.setter
     33     def width(self, value): # Removed in ipywidgets 6.0
---> 34         self.layout.width = value
     35
     36     @property

C:\Users\username\Anaconda3\lib\site-packages\traitlets\traitlets.py in __get__(self, obj, cls)
    552             return self
    553         else:
--> 554             return self.get(obj, cls)
    555
    556     def set(self, obj, value):

C:\Users\username\Anaconda3\lib\site-packages\traitlets\traitlets.py in get(self, obj, cls)
    531                 raise TraitError("No default value found for %s trait of %r"
    532                                  % (self.name, obj))
--> 533             value = self._validate(obj, dynamic_default())
    534             obj._trait_values[self.name] = value
    535             return value

C:\Users\username\Anaconda3\lib\site-packages\ipywidgets\widgets\domwidget.py in _layout_default(self)
     21     layout = Instance(Layout, allow_none=True).tag(sync=True, **widget_serialization)
     22     def _layout_default(self):
---> 23         return Layout()
     24
     25     # width, height, padding, margin border properties rebinding to the layout attribute.

C:\Users\username\Anaconda3\lib\site-packages\ipywidgets\widgets\widget.py in __init__(self, **kwargs)
    182
    183         Widget._call_widget_constructed(self)
--> 184         self.open()
    185
    186     def __del__(self):

C:\Users\username\Anaconda3\lib\site-packages\ipywidgets\widgets\widget.py in open(self)
    201                 args['comm_id'] = self._model_id
    202
--> 203             self.comm = Comm(**args)
    204             if buffers:
    205                 # FIXME: workaround ipykernel missing binary message support in open-on-init

C:\Users\username\Anaconda3\lib\site-packages\ipykernel\comm\comm.py in __init__(self, target_name, data, metadata, buffers, **kwargs)
     54         if self.primary:
     55             # I am primary, open my peer.
---> 56             self.open(data=data, metadata=metadata, buffers=buffers)
     57         else:
     58             self._closed = False

C:\Users\username\Anaconda3\lib\site-packages\ipykernel\comm\comm.py in open(self, data, metadata, buffers)
     81         if data is None:
     82             data = self._open_data
---> 83         comm_manager = getattr(self.kernel, 'comm_manager', None)
     84         if comm_manager is None:
     85             raise RuntimeError("Comms cannot be opened without a kernel "

C:\Users\username\Anaconda3\lib\site-packages\traitlets\traitlets.py in __get__(self, obj, cls)
    552             return self
    553         else:
--> 554             return self.get(obj, cls)
    555
    556     def set(self, obj, value):

C:\Users\username\Anaconda3\lib\site-packages\traitlets\traitlets.py in get(self, obj, cls)
    531                 raise TraitError("No default value found for %s trait of %r"
    532                                  % (self.name, obj))
--> 533             value = self._validate(obj, dynamic_default())
    534             obj._trait_values[self.name] = value
    535             return value

C:\Users\username\Anaconda3\lib\site-packages\traitlets\traitlets.py in _validate(self, obj, value)
    587             return value
    588         if hasattr(self, 'validate'):
--> 589             value = self.validate(obj, value)
    590         if obj._cross_validation_lock is False:
    591             value = self._cross_validate(obj, value)

C:\Users\username\Anaconda3\lib\site-packages\traitlets\traitlets.py in validate(self, obj, value)
   1679             return value
   1680         else:
-> 1681             self.error(obj, value)
   1682
   1683     def info(self):

C:\Users\username\Anaconda3\lib\site-packages\traitlets\traitlets.py in error(self, obj, value)
   1526                 % (self.name, self.info(), msg)
   1527
-> 1528         raise TraitError(e)
   1529
   1530

TraitError: The 'kernel' trait of a Comm instance must be a Kernel, but a value of class 'NoneType' (i.e. None) was specified.

**Comment by ricklupton** [comment]
You'll get this error if you try to run this in an IPython terminal, not in the notebook. Is that what you're doing? The SankeyWidget only works in the Jupyter notebook.

**Comment by ricklupton** [comment]
Closing now but let us know if this is still an issue.
