### ISSUE TITLE
first node has to be called 'start' for this to work

### ISSUE THREAD

**Issue by chananshgong** [ricklupton/ipysankeywidget#9]
Unless I tell it to name the first node 'start' it won't work

**Comment by ricklupton** [comment]
I'm not sure what you're trying to do. The example in [the first example notebook](https://github.com/ricklupton/ipysankeywidget/blob/master/examples/SankeyWidget%20Example.ipynb) still works if you change it like this, so the first node is called `"Z"` rather than `"start"`:

```python
links = [
    {'source': 'Z', 'target': 'A', 'value': 2},
    {'source': 'A', 'target': 'B', 'value': 2},
    {'source': 'B', 'target': 'Z', 'value': 0.2},
    {'source': 'C', 'target': 'A', 'value': 2},
    {'source': 'A', 'target': 'C', 'value': 2},
]
```
